In [64]:
import numpy as np
import pandas as pd

In [65]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [66]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [67]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [68]:
model= Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [69]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [70]:
model.get_weights()

[array([[-0.68900865,  1.1834422 ],
        [ 0.96151054,  1.1581119 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.03458202],
        [-0.14926696]], dtype=float32),
 array([0.], dtype=float32)]

In [71]:
new_weights = [np.array([[0.1,0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],
                         [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [72]:
model.set_weights(new_weights)

In [73]:
from keras import optimizers

optimizer = optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [74]:
X_train = df[['cgpa', 'profile_score']]
y_train = df[['lpa']]
history = model.fit(X_train, y_train, epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 27.9075  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.5988 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2459 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9387 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.5850 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.2047
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.8276 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4645 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0571 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.7048 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.2449
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8202 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.4133 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.9250 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.5259 
Epoch 16/75
4/4 ━━